---
- name: Hello World Playbook
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Print Hello World
      debug:
        msg: "Hello World UPDATED"

    - name: SSM Response
      debug:
        msg: "SSM is True"
      when: SSM is defined and SSM == "True"
